version: 0.1
log:
  fields:
    service: registry
    environment: d.it
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  maintenance:
    uploadpurging:
      enabled: true
      age: 72h
      interval: 24h  
      dryrun: false
auth:
  htpasswd:
    realm: Registry Realm
    path: /auth/htpasswd    
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3